typography_spectrum: 0.16997993201948702
color:
  brandStrength: 0.5255553643219173
  lightness: 0.5908957885112613
  saturation: 0.7352868390735239
  rhythmicContrast: 0.17565294401720166
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.03195805149152875
name: ShadowGirl
title: SHADOWGIRL
description: 'Between light and dark, day and night'
